server.port: 8081

spring:
  job:
    name: ${job.name:NONE}

  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/netflix
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234

  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
      # ddl-auto: update
    generate-ddl: false
    # generate-ddl: true
    open-in-view: false
    database: mysql
    show-sql: true


  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
      -
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4998466b2aa7a433c35899d6ac98066b
            client-secret: 5PinaTuPbHxZ2GuhYaGpmTYSyD5ivoec
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao" # 프론트가 없기 때문에 바로 백엔드로 디이렉팅
            scope: profile_nickname
            client-authentication-method: client_secret_post
          naver:
            client-id: pFVGanomzDwmq3CIcpgA
            client-secret: 4uX5BIga1v
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            scope: nickname
            client-authentication-method: client_secret_basic
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

jwt:
  # openssl rand -hex 32
  secret: 776cfd7c55dc4bd45a767db72fc005eadf7f72ca61c0a8edae1ed19cc2881236
  expire:
    access-token: 1
    refresh-token: 24
