spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3307/netflix?useUnicode=yes&characterEncoding=UTF-8&rewriteBatchedStatements=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
    generate-ddl: false
    # generate-ddl: true
    open-in-view: false
    show-sql: true

  flyway:
    locations: classpath:flyway
    baseline-on-migrate: true
    baseline-version: 1
    enabled: true