spring:
  config:
    import:
      - 'classpath:adapter-http-property.yml'
      - 'classpath:adapter-persistence-property.yml'
      - 'classpath:adapter-redis-property.yml'
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 4998466b2aa7a433c35899d6ac98066b
            client-secret: 5PinaTuPbHxZ2GuhYaGpmTYSyD5ivoec
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:3000/login/oauth2/code/kakao"
            scope: profile_nickname
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

jwt:
  # openssl rand -hex 32
  secret: 776cfd7c55dc4bd45a767db72fc005eadf7f72ca61c0a8edae1ed19cc2881236
  expire:
    access-token: 1
    refresh-token: 24
